# kitty 한영 전환안될 때 kitty 데스크탑 command를 아래와 같이 수정할것
# fctix-5를 사용함
Exec=env GTK_IM_MODULE=fcitx XMODIFIERS=@im=fcitx QT_IM_MODULE=fcitx GLFW_IM_MODULE=ibus kitty

#font_family NanumGothicCoding
#font_size 13.0
font_family D2Coding
